# WARNING: This is a DEVELOPMENT docker-compose file, it should not be used for production.
version: "3"
services:

  npm:
    image: jc21/nginx-proxy-manager-base:latest
    ports:
      - 80:80
      - 81:81
      - 43:443
    environment:
      - NODE_ENV=development
      - FORCE_COLOR=1
    volumes:
      - npm_data:/data
      - le_data:/etc/letsencrypt
      - .:/app
    working_dir: /app
    depends_on:
      - db
    command: node --max_old_space_size=250 --abort_on_uncaught_exception node_modules/nodemon/bin/nodemon.js

  db:
    image: jc21/mariadb-aria
    environment:
      MYSQL_ROOT_PASSWORD: "npm"
      MYSQL_DATABASE: "npm"
      MYSQL_USER: "npm"
      MYSQL_PASSWORD: "npm"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  npm_data:
  le_data:
  db_data:
