#!/bin/bash -e

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

CYAN='\E[1;36m'
BLUE='\E[1;34m'
RED='\E[1;31m'
GREEN='\E[1;32m'
RESET='\E[0m'

# Ensure docker-compose exists
if hash docker 2>/dev/null; then
	cd "${DIR}/.."
	echo -e "${BLUE}❯ ${CYAN}Build Cleanup ...${RESET}"

	docker run --rm -e CI=true -v "$(pwd):/app" -w /app node:alpine rm -rf \
		/app/frontend/node_modules \
		/app/docs/node_modules \
		/app/docs/.vuepress/dist

	echo -e "${BLUE}❯ ${GREEN}Build Cleanup Complete${RESET}"
else
	echo -e "${RED}❯ docker command is not available${RESET}"
fi
