#!/bin/bash -e

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RED='\E[1;31m'
RESET='\E[0m'

COMPOSE_PROJECT_NAME="npmdev"
COMPOSE_FILE="docker/docker-compose.dev.yml"
export COMPOSE_FILE COMPOSE_PROJECT_NAME

# Ensure docker-compose exists
if hash docker-compose 2>/dev/null; then
	cd "${DIR}/.."
	docker-compose exec npm sqlite3 /data/nginxproxymanager.db
else
	echo -e "${RED}❯ docker-compose command is not available${RESET}"
fi
